#!/usr/bin/env python3
"""Copy the ABI of each deployed contract out of the Foundry build into `abi/`.

    forge build --root contracts
    uv run python packages/protocol/tools/export_abi.py            # write
    uv run python packages/protocol/tools/export_abi.py --check    # fail on drift

Why the ABI is committed rather than read from `contracts/out/`: the indexer, the reconstruction
tool and the web client all decode events and calldata, and none of them should need a Solidity
toolchain to do it. `contracts/out/` is git-ignored build output, so a consumer that read from it
would work on a developer's machine and fail in a container.

Why `--check` exists: a committed copy of generated data is a lie waiting to happen. The contract
gate runs `forge build` and then this check, so an ABI change that was not exported fails the
build rather than surfacing later as an event the indexer cannot decode.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[3]
BUILD_DIR = REPO_ROOT / "contracts" / "out"
ABI_DIR = REPO_ROOT / "packages" / "protocol" / "abi"

#: The two contracts that are actually deployed. `INegotiationExchange` is not exported: its ABI
#: is a subset of the exchange's, and two overlapping copies of the same event definitions is one
#: more thing that can disagree.
CONTRACTS = (
    ("NegotiationExchange", "NegotiationExchange.sol"),
    ("MockERC20", "MockERC20.sol"),
)


def artefact_for(contract: str, source: str) -> dict[str, Any]:
    path = BUILD_DIR / source / f"{contract}.json"
    if not path.is_file():
        raise SystemExit(
            f"{path} not found. Run `forge build --root contracts` first: this script copies the "
            "build's ABI rather than deriving it, so there is nothing to export without a build."
        )
    artefact: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
    return artefact


def rendered(contract: str, source: str) -> str:
    artefact = artefact_for(contract, source)
    document = {
        "contract": contract,
        "source": f"contracts/src/{source}",
        "protocol_version": "1",
        "solc": artefact["metadata"]["compiler"]["version"],
        "note": (
            "Generated by packages/protocol/tools/export_abi.py from the Foundry build. "
            "Do not edit: the contract is the source, docs/protocol.md is the specification."
        ),
        "abi": artefact["abi"],
    }
    return json.dumps(document, indent=2) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare with the committed files and exit 1 on any difference",
    )
    args = parser.parse_args(argv)

    ABI_DIR.mkdir(parents=True, exist_ok=True)
    stale: list[str] = []

    for contract, source in CONTRACTS:
        target = ABI_DIR / f"{contract}.json"
        content = rendered(contract, source)

        if not args.check:
            target.write_text(content, encoding="utf-8")
            print(f"wrote {target.relative_to(REPO_ROOT)}")
            continue

        existing = target.read_text(encoding="utf-8") if target.is_file() else ""
        if existing != content:
            stale.append(target.relative_to(REPO_ROOT).as_posix())

    if stale:
        print(
            "ABI artefacts are out of date:\n  "
            + "\n  ".join(stale)
            + "\n\nRun: uv run python packages/protocol/tools/export_abi.py",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
