"""Persistence: models, migrations and repositories (docs/data_model.md).

The rest of the backend imports from here: `Database` to open a unit of work, the repository
protocols to type against, the records and enums that cross the boundary, and the errors a refused
write raises. SQLAlchemy stays inside this package (`.importlinter`, `sessions-stay-in-db`).
"""

from api.db.database import Database
from api.db.enums import (
    TX_STATUSES_NOT_LIVE,
    ActionKind,
    ActionStatus,
    OperationStatus,
    OutcomeKind,
    Party,
    PartyOrOperator,
    PolicyKind,
    RunMode,
    RunState,
    SnapshotStage,
    TokenRole,
    TurnState,
    TxKind,
    TxStatus,
)
from api.db.errors import (
    CheckViolationError,
    ConstraintViolationError,
    DuplicateError,
    ForeignKeyViolationError,
    ImmutableRowError,
    LeaseLostError,
    NotFoundError,
    PersistenceError,
)
from api.db.protocols import UnitOfWork
from api.db.records import (
    BalanceSnapshotRecord,
    ChainEventRecord,
    DecisionRecord,
    DeploymentRecord,
    Inclusion,
    LeaseRecord,
    MandateVersionRecord,
    NewBalanceSnapshot,
    NewChainEvent,
    NewDecision,
    NewMandate,
    NewOperation,
    NewOutboxTx,
    NewRun,
    NewSignedAction,
    NewTurn,
    NewWallet,
    OperationRecord,
    OutboxRecord,
    Outcome,
    RunEventRecord,
    RunMetricsRecord,
    RunRecord,
    ScenarioRecord,
    SignedActionRecord,
    TurnRecord,
    WalletRecord,
    mandate_document,
)

__all__ = [
    "TX_STATUSES_NOT_LIVE",
    "ActionKind",
    "ActionStatus",
    "BalanceSnapshotRecord",
    "ChainEventRecord",
    "CheckViolationError",
    "ConstraintViolationError",
    "Database",
    "DecisionRecord",
    "DeploymentRecord",
    "DuplicateError",
    "ForeignKeyViolationError",
    "ImmutableRowError",
    "Inclusion",
    "LeaseLostError",
    "LeaseRecord",
    "MandateVersionRecord",
    "NewBalanceSnapshot",
    "NewChainEvent",
    "NewDecision",
    "NewMandate",
    "NewOperation",
    "NewOutboxTx",
    "NewRun",
    "NewSignedAction",
    "NewTurn",
    "NewWallet",
    "NotFoundError",
    "OperationRecord",
    "OperationStatus",
    "OutboxRecord",
    "Outcome",
    "OutcomeKind",
    "Party",
    "PartyOrOperator",
    "PersistenceError",
    "PolicyKind",
    "RunEventRecord",
    "RunMetricsRecord",
    "RunMode",
    "RunRecord",
    "RunState",
    "ScenarioRecord",
    "SignedActionRecord",
    "SnapshotStage",
    "TokenRole",
    "TurnRecord",
    "TurnState",
    "TxKind",
    "TxStatus",
    "UnitOfWork",
    "WalletRecord",
    "mandate_document",
]
